// Auto-generated by boneyard-js CLI
// This file will be regenerated when you run: npx boneyard-js build http://localhost:3000

export default {
  // Skeleton definitions will be auto-populated here
};
